start-at-login                = false
accordion-padding             = 0
default-root-container-layout = 'accordion'

[gaps]
    inner.horizontal = 5
    inner.vertical =   5x5
    outer.left =       10
    outer.bottom =     10
    outer.top =        10
    outer.right =      10

[mode.main.binding]
    ctrl-minus = 'mode hop'
    alt-tab    = 'mode hop'

[mode.hop.binding]
    esc       = ['reload-config', 'mode main']
    ctrl-g    = ['reload-config', 'mode main']
    f         = ['layout floating tiling', 'mode main']
    period    = ['layout tiles horizontal vertical', 'mode main']
    comma     = ['layout accordion horizontal vertical', 'mode main']
    h         = 'focus left'
    j         = 'focus down'
    k         = 'focus up'
    l         = 'focus right'
    shift-h   = 'move left'
    shift-j   = 'move down'
    shift-k   = 'move up'
    shift-l   = 'move right'
    minus     = 'resize smart -50'
    equal     = 'resize smart +50'

[[on-window-detected]]
	if.app-id                       = "org.mozilla.librewolf"
	if.window-title-regex-substring = "Picture-in-Picture"
	run                             = "layout floating"