filetype on
syntax on

" colorscheme base16-base

hi LineNr ctermbg=none ctermfg=1

set autoindent
set autoread
set background=dark
set cmdheight=1
set cursorlineopt=screenline
set expandtab
set foldcolumn=0
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=3
set listchars=trail:%
set mouse=a
set nocompatible
set notermguicolors
set nowrap
set number
set report=0
set shiftwidth=4
set shortmess+=c
set showcmd
set smarttab
set softtabstop=0
set splitbelow
set splitright
set tabstop=4
set undodir=~/.vimundo/
set undofile
set updatetime=300

let &t_Cs = "\e[4:3m"
let &t_Ce = "\e[4:0m"

let semhighlight=1
 
let mapleader = " "
nnoremap <silent> <leader>nonum     :set nonumber<CR>
nnoremap <silent> <leader>num       :set number<CR>
nnoremap <silent> <leader>ws        :call TrimWhitespace()<CR>
nnoremap <silent> <leader>x         :bd<CR>
nnoremap <silent> €                 $
nnoremap Q <Nop>
nnoremap U <C-r>

" Hoppa mellan buffer med tab
nnoremap <silent> <C-S-i> :bp<cr>
nnoremap <silent> <C-i> :bn<cr>
nnoremap <silent> <S-Tab> :bp<cr>
nnoremap <silent> <Tab> :bn<cr>

autocmd BufRead */notes* nnoremap <silent> <SPACE> :call Check_mark()<CR>
autocmd BufRead */notes* set tabstop=4 | set shiftwidth=4
autocmd BufRead */tmpaaab* set syntax=config

function! HeaderToggle()
    let filename = expand("%:t")
    if filename =~ ".cpp$"
        execute "e %:r.hpp"
    elseif filename =~ ".hpp$"
        execute "e %:r.cpp"
    elseif filename =~ ".c$"
        execute "e %:r.h"
    elseif filename =~ ".h"
        execute "e %:r.c"
    endif
endfunction

nnoremap <silent> <leader>hp :call HeaderToggle()<cr>

function! g:Check_mark()
    if getline('.') =~ '\[\ \]'
        .s/\[\ \]/\[x\]/g
    elseif getline('.') =~ '\[x\]'
        .s/\[x\]/\[\ \]/g
    endif
endfunction

function! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun
